name: Job Concurrency

on:
  push:
    
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: nginx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: production-deploy
      cancel-in-progress: true

    steps:
    - name: Docker Login
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $CONTAINER_REGISTRY

    - name: Docker Push
      run: |
        docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest