name: Matrix Configuration
on: 
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      # if fail-fast is set to true, the matrix will stop running after the first failure and if set to false, the matrix will continue to run even after a failure happens in any of the jobs. 
      fail-fast: false
      # max-parallel is used to define the maximum number of jobs that can run at the same time.
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        image: [hello-world, alpine]
        exclude:
          - image: alpine
            os: windows-latest
         
        include:
          - image: amd64/alpine
            os: ubuntu-20.04

    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker details
        run: docker info
      
      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.image }}